version: '2'
networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: em1 # Change your iface here (eth0 / wlan0 / etc...)
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.0/24
